CREATE DATABASE BTL2
GO
USE BTL2
GO

CREATE TABLE KHACHHANG
(
    CCCD VARCHAR(20) PRIMARY KEY,
    HOTEN VARCHAR(20) NOT NULL ,
    GIOITINH VARCHAR(20),
    NGAYSINH DATETIME ,
    EMAIL VARCHAR(20),
    DIEMTICHLUY INT NOT NULL,
    SONHA INT ,
    DUONG VARCHAR(20),
    XAPHUONG VARCHAR(20),
    QUANHUYEN VARCHAR(20),
    TINHTHANHPHO VARCHAR(20)
)

CREATE TABLE TAIKHOAN
(
    MATAIKHOAN VARCHAR(20) PRIMARY KEY,
    TENDANGNHAP VARCHAR(20) NOT NULL,
    MATKHAU VARCHAR(20) NOT NULL,
    CCCD VARCHAR(20) NOT NULL,
    CONSTRAINT FK_TAIKHOAN FOREIGN KEY (CCCD) REFERENCES KHACHHANG(CCCD)
)

CREATE TABLE VOUCHER
(
    MAVOUCHER VARCHAR(20) PRIMARY KEY ,
    TANGMON VARCHAR(20),
    QUATANG VARCHAR(20),
    GIAMGIATHEOTIEN VARCHAR(100),
    GIAMGIATHEOPHANTRAM VARCHAR(20),
    NGAYBATDAU DATETIME NOT NULL,
    NGAYHETHAN DATETIME NOT NULL,
)

CREATE TABLE FOODANDDRINK
(
    TEN VARCHAR(20),
    VERSION VARCHAR(20),
    GIA VARCHAR(20) NOT NULL,
    NGUYENLIEU VARCHAR(100) NOT NULL,
    MOTA VARCHAR(20) NOT NULL,
    YEUTHICH VARCHAR(20),
    CONSTRAINT PK_FOODANDDRINK PRIMARY KEY (TEN,VERSION)
)


CREATE TABLE NHANVIEN
(
    MANHANVIEN VARCHAR(20) PRIMARY KEY,
    HOTEN VARCHAR(20) NOT NULL,
    GIOITINH VARCHAR(20) NOT NULL,
    NGAYSINH DATETIME NOT NULL,
    DIACHI VARCHAR(20) NOT NULL,
    NGAYBATDAULAM DATETIME NOT NULL,
    TKNGANHANG VARCHAR(20) NOT NULL,
    BANGCAP VARCHAR(20),
    LUONGTHEOTHANG VARCHAR(20) NOT NULL,
    LUONGTHEOGIO VARCHAR(20) NOT NULL,
    MANVQUANLY VARCHAR(20) NOT NULL,
    CONSTRAINT FK_NHANVIEN FOREIGN KEY (MANVQUANLY) REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE PHUCVU
(
    MANHANVIEN VARCHAR(20) PRIMARY KEY,
    CONSTRAINT FK_PHUCVU FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)


CREATE TABLE DAUBEP
(
    MANHANVIEN VARCHAR(20) PRIMARY KEY,
    CONSTRAINT FK_DAUBEP FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)


CREATE TABLE THUNGAN
(
    MANHANVIEN VARCHAR(20) PRIMARY KEY,
    CONSTRAINT FK_THNGAN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)


CREATE TABLE TTLIENHE
(
    MANHANVIEN VARCHAR(20),
    EMAIL VARCHAR(20),
    SDT VARCHAR(20),
    CONSTRAINT PK_TTLIENHENV PRIMARY KEY(MANHANVIEN,EMAIL,SDT),
    CONSTRAINT FK_TTLIENHE FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)


CREATE TABLE MONAN
(
    TEN VARCHAR(20),
    VERSION VARCHAR(20),
    CACHCHEBIEN VARCHAR(1000) NOT NULL,
    CANHBAODIUNG VARCHAR(20) ,
    CONSTRAINT PK_MONAN1 PRIMARY KEY (TEN,VERSION),
    CONSTRAINT FK_MONAN2 FOREIGN KEY (TEN,VERSION) REFERENCES FOODANDDRINK(TEN,VERSION)
)


CREATE TABLE DOUONG
(
    TEN VARCHAR(20) ,
    VERSION VARCHAR(20) ,
    XUATXU VARCHAR (20) NOT NULL,
    CONSTRAINT PK_DOUONG1 PRIMARY KEY (TEN,VERSION),
    CONSTRAINT FK_DOUONG2 FOREIGN KEY (TEN,VERSION) REFERENCES FOODANDDRINK(TEN,VERSION)
)


CREATE TABLE SDTKHACHHANG
(
    CCCD VARCHAR(20),
    SDT VARCHAR(20) ,
    CONSTRAINT PK_SDTKHACHHANG PRIMARY KEY (CCCD, SDT)
)


CREATE TABLE PHONG
(
    SOPHONG INT PRIMARY KEY,
    TINHTRANG VARCHAR(20) NOT NULL,
    SUCCHUA INT NOT NULL,
    LOAI VARCHAR(20) NOT NULL
)


CREATE TABLE BAN
(
    SOPHONG INT ,
    SOBAN INT ,
    TINHTRANG VARCHAR(20) NOT NULL,
    SUCCHUA VARCHAR(20) NOT NULL
    CONSTRAINT PK_BAN PRIMARY KEY (SOPHONG,SOBAN)
)


CREATE TABLE DHHD
(
    MADONHANG VARCHAR(20) PRIMARY KEY,
    CCCD_KH VARCHAR(20) NOT NULL,
    TRANGTHAI VARCHAR(20) ,
    NGAYDAT DATETIME ,
    NGAYGIAO DATETIME,
    DIACHIGIAOHANG VARCHAR(20),
    SOPHONG INT ,
    SOBAN INT,
    MAHOADON VARCHAR(20) NOT NULL,
    MAVOUCHER VARCHAR(20) ,
    MANVTHUNGAN VARCHAR(20) NOT NULL,
    PHUONGTHUCTHANHTOAN VARCHAR(20) NOT NULL,
    NGAYTAOHOADON DATETIME NOT NULL,
    CONSTRAINT FK_DHHD_KH FOREIGN KEY (CCCD_KH) REFERENCES KHACHHANG(CCCD),
    CONSTRAINT FK_DHHD_VOUVHER FOREIGN KEY (MAVOUCHER) REFERENCES VOUCHER(MAVOUCHER),
    CONSTRAINT FK_DHHD_THUNGAN FOREIGN KEY (MANVTHUNGAN) REFERENCES THUNGAN(MANHANVIEN)
)


CREATE TABLE DONVIVANCHUYEN
(
    MADONVI VARCHAR(20)  PRIMARY KEY,
    TENDONVI VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    SONHA INT NOT NULL,
    DUONG VARCHAR(20) NOT NULL,
    XAPHUONG VARCHAR(20) NOT NULL,
    QUANHUYEN VARCHAR(20) NOT NULL,
    TINHTHANHPHO VARCHAR(20) NOT NULL,
)


CREATE TABLE PHUCVU_PHONG
(
    MANVPHUCVU VARCHAR(20),
    SOPHONG INT NOT NULL,
    CONSTRAINT PK_PHUCVU_PHONG PRIMARY KEY (MANVPHUCVU,SOPHONG),
    CONSTRAINT FK_MANVPHUCVU FOREIGN KEY (MANVPHUCVU) REFERENCES PHUCVU(MANHANVIEN),
    CONSTRAINT FK_SOPHONG FOREIGN KEY (SOPHONG) REFERENCES PHONG(SOPHONG)
)


CREATE TABLE CHEBIEN
(
    TEN VARCHAR(20),
    VERSION VARCHAR(20),
    MANVDAUBEP VARCHAR(20) ,
    TENDAUBEP VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CHEBIEN PRIMARY KEY (TEN,VERSION,MANVDAUBEP),
    CONSTRAINT FK_TENMON FOREIGN KEY (TEN,VERSION) REFERENCES MONAN(TEN,VERSION),
    CONSTRAINT FK_MANVDAUBEP FOREIGN KEY (MANVDAUBEP) REFERENCES DAUBEP(MANHANVIEN)
)


CREATE TABLE DONHANG_BAN
(
    MADONHANG VARCHAR(20),
    SOPHONG INT,
    SOBAN INT,
    CONSTRAINT PK_DONHANG_BAN PRIMARY KEY (MADONHANG,SOPHONG,SOBAN),
    CONSTRAINT FK_DONHANG_BAN FOREIGN KEY (MADONHANG) REFERENCES DHHD(MADONHANG)
)


CREATE TABLE VANCHUYEN
(
    MDH VARCHAR(20) PRIMARY KEY,
    MADVVANCHUYEN VARCHAR(20) NOT NULL,
    SHIPPERN VARCHAR(20) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    MAVANDON VARCHAR(20) NOT NULL,
    CONSTRAINT FK_VANCHUYEN_MDH FOREIGN KEY (MDH) REFERENCES DHHD(MADONHANG),
    CONSTRAINT FK_DVVANCHUYEN FOREIGN KEY (MADVVANCHUYEN) REFERENCES DONVIVANCHUYEN(MADONVI)
)


CREATE TABLE SDTDVVC
(
    MADONVI VARCHAR(20),
    SDT VARCHAR(20) ,
    CONSTRAINT PK PRIMARY KEY (MADONVI,SDT),
    CONSTRAINT FK FOREIGN KEY (MADONVI) REFERENCES DONVIVANCHUYEN(MADONVI)
)

CREATE TABLE FD_DH
(
    TEN VARCHAR(20) ,
    VERSION VARCHAR(20) ,
    MDH VARCHAR(20) ,
    GIA VARCHAR(20) NOT NULL,
    SOLUONG INT NOT NULL,
    CONSTRAINT PK_FD_DH PRIMARY KEY (TEN,VERSION,MDH),
    CONSTRAINT FK_FD_DH_TENMON FOREIGN KEY (TEN,VERSION) REFERENCES MONAN(TEN,VERSION),
    CONSTRAINT FK_FD_DH_MDH FOREIGN KEY (MDH) REFERENCES DHHD(MADONHANG)
)


CREATE TABLE FD_VOUCHER_APDUNG
(
    TEN VARCHAR(20),
    VERSION VARCHAR(20),
    MAVOUCHER VARCHAR(20),
    SOLUONG INT NOT NULL,
    CONSTRAINT PK_FD_VOUVHER_APDUNG PRIMARY KEY (TEN,VERSION,MAVOUCHER),
    CONSTRAINT FK_FD_VOUCHER_APDUNG_TENMON FOREIGN KEY (TEN,VERSION) REFERENCES MONAN(TEN,VERSION),
    CONSTRAINT FK_FD_VOUCHER_APDUNG_MAVOUCHER FOREIGN KEY (MAVOUCHER) REFERENCES VOUCHER(MAVOUCHER)
)


CREATE TABLE FD_VOUCHER_TANG
(
    TEN VARCHAR(20),
    VERSION VARCHAR(20) ,
    MAVOUCHER VARCHAR(20),
    SOLUONG INT NOT NULL ,
    CONSTRAINT PK_FD_VOUCHER_TANG PRIMARY KEY (TEN,VERSION,MAVOUCHER),
    CONSTRAINT FK_FD_VOUVHER_TANG_TENMON FOREIGN KEY (TEN,VERSION) REFERENCES MONAN(TEN,VERSION),
    CONSTRAINT FK_FD_VOUVHER_TANG_MAVOUCHER FOREIGN KEY (MAVOUCHER) REFERENCES VOUCHER(MAVOUCHER)
)
