--2.1.a
ALTER PROC proc_insert_food_and_drink
    @LOAI VARCHAR(100) = NULL,
    @TEN VARCHAR(100) = NULL,
    @VERSION VARCHAR(100) = NULL,
    @GIA BIGINT = NULL,
    @NGUYENLIEU VARCHAR(100) = NULL,
    @MOTA VARCHAR(100) = NULL,
    @NGAYTHEM DATE = NULL,
    @TINHTRANG VARCHAR(100) = NULL,
    @YEUTHICH VARCHAR(100) = NULL,
    @XUATXU VARCHAR(100) = NULL,
    @CACHCHEBIEN VARCHAR(100) = NULL,
    @CANHBAODIUNG VARCHAR(100) = NULL
AS
BEGIN
    DECLARE @NULLCOLUMN TABLE(COLUMNNAME VARCHAR(100))
    IF(@TEN IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot TEN')
    IF(@VERSION IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot VERSION')
    IF(@GIA IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot GIA')
    IF(@NGUYENLIEU IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot NGUYENLIEU')
    IF(@MOTA IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot MOTA')
    IF(@NGAYTHEM IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot NGAYTHEM')
    IF(@TINHTRANG IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot TINHTRANG')
    IF(@YEUTHICH IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot YEUTHICH')
    IF(@XUATXU IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot XUATXU')
    IF(@CACHCHEBIEN IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot CACHCHEBIEN')
    IF(@CANHBAODIUNG IS NULL) INSERT INTO @NULLCOLUMN
    VALUES('cot CANHBAODIUNG')
    IF(EXISTS(SELECT 1 FROM @NULLCOLUMN))
    BEGIN
        DECLARE @MISSINGCOLUMN VARCHAR(100)
        SELECT @MISSINGCOLUMN = STRING_AGG(COLUMNNAME,',')
        FROM @NULLCOLUMN
        PRINT N'Chua nhap du lieu o '+@MISSINGCOLUMN
        ROLLBACK TRAN
    END
    IF(EXISTS(SELECT 1 FROM FOODANDDRINK
    WHERE @VERSION != VERSION))
    BEGIN
        PRINT N'Khac version mon an'
        ROLLBACK TRAN
    END
    IF EXISTS(SELECT 1
    FROM FOODANDDRINK
    WHERE @TEN = TEN )
    BEGIN
        PRINT N'Trung ten mon an'
        ROLLBACK TRAN
    END
    IF @GIA <=0
    BEGIN
        PRINT N'Gia nhap khong hop le'
        ROLLBACK TRAN
    END
    IF @LOAI = 'DO AN'
    BEGIN
        INSERT INTO FOODANDDRINK
            (TEN,VERSION,GIA,NGUYENLIEU,MOTA,NGAYTHEM,TINHTRANG,YEUTHICH)
        VALUES(@TEN, @VERSION, @GIA, @NGUYENLIEU, @MOTA, @NGAYTHEM, @TINHTRANG, @YEUTHICH)
        INSERT INTO MON_AN
            (TEN,VERSION,CACHCHEBIEN,CANHBAODIUNG)
        VALUES(@TEN, @VERSION, @CACHCHEBIEN, @CANHBAODIUNG)
    END
    ELSE IF @LOAI = 'DO UONG'
    BEGIN
        INSERT INTO FOODANDDRINK
            (TEN,VERSION,GIA,NGUYENLIEU,MOTA,NGAYTHEM,TINHTRANG,YEUTHICH)
        VALUES(@TEN, @VERSION, @GIA, @NGUYENLIEU, @MOTA, @NGAYTHEM, @TINHTRANG, @YEUTHICH)
        INSERT INTO DO_UONG
            (TEN,VERSION,XUATXU)
        VALUES(@TEN, @VERSION, @XUATXU)
    END
END
GO
--2.1.b
ALTER PROC proc_update_food_and_drink
    @TEN VARCHAR(100) = NULL,
    @GIA BIGINT = NULL,
    @NGUYENLIEU VARCHAR(100) = NULL,
    @CACHCHEBIEN VARCHAR(100) = NULL,
    @MOTA VARCHAR(100) = NULL
AS
BEGIN
    IF(NOT EXISTS(SELECT *
    FROM FOODANDDRINK
    WHERE @TEN = TEN))
    BEGIN
        PRINT N'Ten mon khong ton tai!'
        ROLLBACK TRAN
    END
    ELSE IF @GIA <= 0
    BEGIN
        PRINT N'Gia ca khong hop le!'
        ROLLBACK TRAN
    END
    ELSE 
    BEGIN
        DECLARE @GIAFD BIGINT
        SELECT @GIAFD = GIA FROM FOODANDDRINK WHERE @TEN = TEN
        IF(@GIAFD<>@GIA)
        BEGIN
            UPDATE FOODANDDRINK
            SET GIA = @GIA,NGUYENLIEU = @NGUYENLIEU,MOTA = @MOTA
            WHERE @TEN = TEN
            UPDATE MON_AN
            SET CACHCHEBIEN = @CACHCHEBIEN
            WHERE @TEN = TEN
        END
        ELSE 
        BEGIN
            UPDATE FOODANDDRINK
            SET NGUYENLIEU = @NGUYENLIEU,MOTA = @MOTA
            WHERE @TEN = TEN
            UPDATE MON_AN
            SET CACHCHEBIEN = @CACHCHEBIEN
            WHERE @TEN = TEN
        END
    END
END
GO
--2.1.C
ALTER PROC proc_delete_food_and_drink
    @TEN VARCHAR(100) = NULL
AS
BEGIN
    IF(NOT EXISTS(SELECT DISTINCT TEN
    FROM HOADON HD
        JOIN DONHANG_FD DH
        ON HD.MADONHANG = DH.MDH
        WHERE @TEN = TEN))
    BEGIN
        DELETE FROM MON_AN
        WHERE @TEN = TEN
        DELETE FROM FOODANDDRINK
        WHERE @TEN = TEN
    END
    ELSE
    BEGIN
        UPDATE FOODANDDRINK
        SET TINHTRANG = 'Khong ban'
        WHERE @TEN = TEN
    END
END
GO

--2.2.b
CREATE TRIGGER trig_total_cost_of_bill
ON DONHANG_FD
FOR INSERT,UPDATE,DELETE
AS
BEGIN
    UPDATE 
END
GO
--2.3.a
ALTER PROC proc_list_employee_of_room
    @SOPHONG VARCHAR(100) = NULL,
    @NGAYPHUCVU DATE = NULL
AS
BEGIN
    DECLARE @TENNHANVIEN VARCHAR(100)
    SELECT HOTEN
    FROM PHUCVU_PHONG
        JOIN PHUCVU
        ON PHUCVU.MANHANVIEN = PHUCVU_PHONG.MANVPHUCVU
        JOIN NHANVIEN
        ON PHUCVU_PHONG.MANVPHUCVU = NHANVIEN.MANHANVIEN
    WHERE @SOPHONG = SOPHONG AND @NGAYPHUCVU = NGAYPHUCVU
END
GO
--2.3.b



